---
fixtures:
  repositories:
    apache:
      repo: https://github.com/simp/pupmod-simp-apache
      branch: 5.X
    augeasproviders_core:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_core
    augeasproviders_grub:
      branch: 5.X
      repo: https://github.com/simp/augeasproviders_grub
    auditd:
      repo: https://github.com/simp/pupmod-simp-auditd
      branch: 5.X
    compliance_markup:
      repo: https://github.com/simp/pupmod-simp-compliance_markup
      branch: 5.X
    datacat:
      repo: https://github.com/simp/puppet-datacat
      branch: 5.X
    elasticsearch:
      branch: 5.X
      repo: https://github.com/simp/puppet-elasticsearch
    file_concat:
      branch: 5.X
      repo: https://github.com/simp/puppet-lib-file_concat
    grafana:
      ref: 6d426d5ccc52ff23dbbcfc45290dafd224b5d2bc
      repo: https://github.com/simp/puppet-grafana
      branch: 5.X
    haveged:
      ref: simp-master
      repo: https://github.com/simp/puppet-haveged
      branch: 5.X
    iptables:
      repo: https://github.com/simp/pupmod-simp-iptables
      branch: 5.X
    java:
      ref: simp-master
      repo: https://github.com/simp/puppetlabs-java
      branch: 5.X
    logrotate:
      repo: https://github.com/simp/pupmod-simp-logrotate
      branch: 5.X
    oddjob:
      repo: https://github.com/simp/pupmod-simp-oddjob
      branch: 5.X
    openldap:
      repo: https://github.com/simp/pupmod-simp-openldap
      branch: 5.X
    pam:
      repo: https://github.com/simp/pupmod-simp-pam
      branch: 5.X
    pki:
      repo: https://github.com/simp/pupmod-simp-pki
      branch: 5.X
    rsyslog:
      repo: https://github.com/simp/pupmod-simp-rsyslog
      branch: 5.X
    rsync:
      repo: https://github.com/simp/puppet-lib-file_concat
      branch: 5.X
    simp:
      repo: https://github.com/simp/pupmod-simp-simp
      branch: 5.X
    simp_elasticsearch:
      repo: https://github.com/simp/pupmod-simp-simp_elasticsearch
      branch: 5.X
    simpcat:
      repo: https://github.com/simp/pupmod-simp-concat
      branch: 5.X
    simplib:
      repo: https://github.com/simp/pupmod-simp-simplib
      branch: 5.X
    stdlib:
      branch: 5.X
      repo: https://github.com/simp/puppetlabs-stdlib
    sysctl:
      repo: https://github.com/simp/pupmod-simp-sysctl
      branch: 5.X
    tcpwrappers:
      repo: https://github.com/simp/pupmod-simp-tcpwrappers
      branch: 5.X
  symlinks:
    simp_grafana: "#{source_dir}"
